---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: tomcat-servers
  vars :
    http_port: 8080
    https_port: 8081
    admin_username: admin
    admin_password: adminsecret
  remote_user: ec2-user
  become: yes
  become_method: sudo

  roles:
    - selinux
    - tomcat
    - deploy
#    - mysqldb
